CREATE TABLE "TEAM" 
   (	"TEAM_ID" RAW(16) CONSTRAINT "TEA_TEAM_ID_NN" NOT NULL ENABLE, 
	"NAME" VARCHAR2(100) CONSTRAINT "TEA_NAME_NN" NOT NULL ENABLE, 
	 CONSTRAINT "TEAM_PK" PRIMARY KEY ("TEAM_ID")
  USING INDEX  ENABLE
   );

 CREATE TABLE "MASTER_POOL" 
   (	"MASTER_POOL_ID" RAW(16) CONSTRAINT "MPO_MASTER_POOL_ID_NN" NOT NULL ENABLE, 
	"NAME" VARCHAR2(100) CONSTRAINT "MPO_NAME_NN" NOT NULL ENABLE, 
	"START_DATE" DATE CONSTRAINT "MPO_START_DATE_NN" NOT NULL ENABLE, 
	"END_DATE" DATE CONSTRAINT "MPO_END_DATE_NN" NOT NULL ENABLE, 
	 CONSTRAINT "MASTER_POOL_PK" PRIMARY KEY ("MASTER_POOL_ID")
  USING INDEX  ENABLE
   );

CREATE TABLE "POINT" 
   (	"POINT_ID" RAW(16) CONSTRAINT "POI_POINT_ID_NN" NOT NULL ENABLE, 
	"WIN_OR_DRAW_POINT" NUMBER(2,0) CONSTRAINT "POI_WIN_OR_DRAW_POINT_NN" NOT NULL ENABLE, 
	"HOME_RESULT_POINT" NUMBER(2,0) CONSTRAINT "POI_HOME_RESULT_POINT_NN" NOT NULL ENABLE, 
	"AWAY_RESULT_POINT" NUMBER(2,0) CONSTRAINT "POI_AWAY_RESULT_POINT_NN" NOT NULL ENABLE, 
	"DIFFERENCE_POINT" NUMBER(2,0) CONSTRAINT "POI_DIFFERENCE_POINT_NN" NOT NULL ENABLE, 
	"INVERTED_DIFFERENCE_POINT" NUMBER(2,0) CONSTRAINT "POI_INVERTED_DIFFERENCE_POINT_NN" NOT NULL ENABLE, 
	 CONSTRAINT "POI_WIN_OR_DRAW_POINT_CK" CHECK (WIN_OR_DRAW_POINT BETWEEN 0 AND 99) ENABLE, 
	 CONSTRAINT "POI_HOME_RESULT_POINT_CK" CHECK (HOME_RESULT_POINT BETWEEN 0 AND 99) ENABLE, 
	 CONSTRAINT "POI_AWAY_RESULT_POINT_CK" CHECK (AWAY_RESULT_POINT BETWEEN 0 AND 99) ENABLE, 
	 CONSTRAINT "POI_DIFFERENCE_POINT_CK" CHECK (DIFFERENCE_POINT BETWEEN 0 AND 99) ENABLE, 
	 CONSTRAINT "POI_INVERTED_DIFFERENCE_POINT_CK" CHECK (INVERTED_DIFFERENCE_POINT BETWEEN 0 AND 99) ENABLE, 
	 CONSTRAINT "POINT_PK" PRIMARY KEY ("POINT_ID")
  USING INDEX  ENABLE
   );

CREATE TABLE "ROUND" 
   (	"ROUND_ID" RAW(16) CONSTRAINT "ROU_ROUND_ID_NN" NOT NULL ENABLE, 
	"MASTER_POOL_ID" RAW(16) CONSTRAINT "ROU_MASTER_POOL_ID_NN" NOT NULL ENABLE, 
	"NAME" VARCHAR2(100) CONSTRAINT "ROU_NAME_NN" NOT NULL ENABLE, 
	"POINT_ID" RAW(16) CONSTRAINT "ROU_POINT_ID_NN" NOT NULL ENABLE, 
	 CONSTRAINT "ROUND_PK" PRIMARY KEY ("ROUND_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "ROU_MASTER_POOL_FK" FOREIGN KEY ("MASTER_POOL_ID")
	  REFERENCES "MASTER_POOL" ("MASTER_POOL_ID") ENABLE, 
	 CONSTRAINT "ROU_POINT_FK" FOREIGN KEY ("POINT_ID")
	  REFERENCES "POINT" ("POINT_ID") ENABLE
   );

CREATE TABLE "MATCH" 
   (	"MATCH_ID" RAW(16) CONSTRAINT "MAT_MATCH_ID_NN" NOT NULL ENABLE, 
	"HOME_TEAM_ID" RAW(16) CONSTRAINT "MAT_HOME_TEAM_ID_NN" NOT NULL ENABLE, 
	"AWAY_TEAM_ID" RAW(16) CONSTRAINT "MAT_AWAY_TEAM_ID_NN" NOT NULL ENABLE, 
	"ROUND_ID" RAW(16) CONSTRAINT "MAT_ROUND_ID_NN" NOT NULL ENABLE, 
	"MATCH_DATE" DATE CONSTRAINT "MAT_MATCH_DATE_NN" NOT NULL ENABLE, 
	"HOME_RESULT" NUMBER(3,0), 
	"AWAY_RESULT" NUMBER(3,0), 
	"STATUS" NUMBER(1,0) CONSTRAINT "MAT_STATUS_NN" NOT NULL ENABLE, 
	 CONSTRAINT "MATCH_PK" PRIMARY KEY ("MATCH_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "MAT_HOME_RESULT_CK" CHECK (HOME_RESULT BETWEEN 0 AND 999) ENABLE, 
	 CONSTRAINT "MAT_AWAY_RESULT_CK" CHECK (AWAY_RESULT BETWEEN 0 AND 999) ENABLE, 
	 CONSTRAINT "MAT_STATUS_CK" CHECK (STATUS BETWEEN 0 AND 4) ENABLE, 
	 CONSTRAINT "MAT_ROUND_ID" FOREIGN KEY ("ROUND_ID")
	  REFERENCES "ROUND" ("ROUND_ID") ENABLE, 
	 CONSTRAINT "MAT_HOME_TEAM_ID" FOREIGN KEY ("HOME_TEAM_ID")
	  REFERENCES "TEAM" ("TEAM_ID") ENABLE, 
	 CONSTRAINT "MAT_AWAY_TEAM_ID" FOREIGN KEY ("AWAY_TEAM_ID")
	  REFERENCES "TEAM" ("TEAM_ID") ENABLE
   );

CREATE TABLE "GAMBLER" 
   (	"USER_ID" RAW(16) NOT NULL ENABLE, 
	 CONSTRAINT "GAMBLER_PK" PRIMARY KEY ("USER_ID")
  USING INDEX  ENABLE
   );

CREATE TABLE "POOL" 
   (	"POOL_ID" RAW(16) CONSTRAINT "POO_POOL_ID_NN" NOT NULL ENABLE, 
	"MASTER_POOL_ID" RAW(16) CONSTRAINT "POO_MASTER_POOL_ID_NN" NOT NULL ENABLE, 
	"OWNER_GAMBLER_ID" RAW(16) CONSTRAINT "POO_OWNER_GAMBLER_ID_NN" NOT NULL ENABLE, 
	"CREATION_DATE" DATE CONSTRAINT "POO_CREATION_DATE_NN" NOT NULL ENABLE, 
	 CONSTRAINT "POOL_PK" PRIMARY KEY ("POOL_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "POO_MASTER_POOL_FK" FOREIGN KEY ("MASTER_POOL_ID")
	  REFERENCES "MASTER_POOL" ("MASTER_POOL_ID") ENABLE, 
	 CONSTRAINT "POO_GAMBLER_FK" FOREIGN KEY ("OWNER_GAMBLER_ID")
	  REFERENCES "GAMBLER" ("USER_ID") ENABLE
   );

CREATE TABLE "POOL_ENROLLMENT" 
   (	"POOL_ID" RAW(16) CONSTRAINT "PEN_POOL_ID_NN" NOT NULL ENABLE, 
	"GAMBLER_ID" RAW(16) CONSTRAINT "PEN_GAMBLER_ID_NN" NOT NULL ENABLE, 
	"ENROLLMENT_DATE" DATE CONSTRAINT "PEN_ENROLLMENT_DATE_NN" NOT NULL ENABLE, 
	 CONSTRAINT "POOL_ENROLLMENT_PK" PRIMARY KEY ("POOL_ID", "GAMBLER_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "PEN_POOL" FOREIGN KEY ("POOL_ID")
	  REFERENCES "POOL" ("POOL_ID") ENABLE, 
	 CONSTRAINT "PEN_GAMBLER" FOREIGN KEY ("GAMBLER_ID")
	  REFERENCES "GAMBLER" ("USER_ID") ENABLE
   );

CREATE TABLE "BET" 
   (	"POOL_ID" RAW(16) CONSTRAINT "BET_POOL_ID_NN" NOT NULL ENABLE, 
	"GAMBLER_ID" RAW(16) CONSTRAINT "BET_GAMBLER_ID_NN" NOT NULL ENABLE, 
	"MATCH_ID" RAW(16) CONSTRAINT "BET_MATCH_ID_NN" NOT NULL ENABLE, 
	"HOME_TEAM_VALUE" NUMBER(3,0) CONSTRAINT "BET_HOME_TEAM_VALUE_NN" NOT NULL ENABLE, 
	"AWAY_TEAM_VALUE" NUMBER(3,0) CONSTRAINT "BET_AWAY_TEAM_VALUE_NN" NOT NULL ENABLE, 
	 CONSTRAINT "BET_PK" PRIMARY KEY ("POOL_ID", "GAMBLER_ID", "MATCH_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "BET_HOME_TEAM_VALUE_CK" CHECK (HOME_TEAM_VALUE BETWEEN 0 AND 999) ENABLE, 
	 CONSTRAINT "BET_AWAY_TEAM_VALUE_CK" CHECK (AWAY_TEAM_VALUE BETWEEN 0 AND 999) ENABLE, 
	 CONSTRAINT "BET_POOL_ENROLLMENT_FK" FOREIGN KEY ("POOL_ID", "GAMBLER_ID")
	  REFERENCES "POOL_ENROLLMENT" ("POOL_ID", "GAMBLER_ID") ENABLE, 
	 CONSTRAINT "BET_MATCH_FK" FOREIGN KEY ("MATCH_ID")
	  REFERENCES "MATCH" ("MATCH_ID") ENABLE
   ); 
